version: '3.8'

services:
  icloud-backup-test:
    build:
      context: ../hassio-icloud-backup
      dockerfile: Dockerfile
    container_name: icloud-backup-test
    ports:
      - "8099:8099"
    environment:
      - APPLE_ID=${APPLE_ID:-your-email@example.com}
      - APPLE_PASSWORD=${APPLE_PASSWORD:-your-app-specific-password}
      - BACKUP_SOURCE=/backup
      - ICLOUD_FOLDER=HomeAssistantBackups
      - RETENTION_DAYS=30
    volumes:
      # Mount the code for live editing
      - ../hassio-icloud-backup/run.sh:/run.sh:ro
      - ../hassio-icloud-backup/setup_server.py:/setup_server.py:ro
      # Data persistence
      - ./test-data:/data
      # Test backup directory
      - ./test-backups:/backup:ro
    stdin_open: true
    tty: true
